/* tslint:disable */
/* eslint-disable */
/**
 * Makielak API
 * This is a makielak API documentation.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ContentResponseData } from './ContentResponseData';
import {
    ContentResponseDataFromJSON,
    ContentResponseDataFromJSONTyped,
    ContentResponseDataToJSON,
} from './ContentResponseData';

/**
 * 
 * @export
 * @interface ContentResponse
 */
export interface ContentResponse {
    /**
     * 
     * @type {ContentResponseData}
     * @memberof ContentResponse
     */
    data?: ContentResponseData;
    /**
     * 
     * @type {number}
     * @memberof ContentResponse
     */
    statusCode?: number;
    /**
     * 
     * @type {string}
     * @memberof ContentResponse
     */
    error?: string;
}

/**
 * Check if a given object implements the ContentResponse interface.
 */
export function instanceOfContentResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ContentResponseFromJSON(json: any): ContentResponse {
    return ContentResponseFromJSONTyped(json, false);
}

export function ContentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContentResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : ContentResponseDataFromJSON(json['data']),
        'statusCode': !exists(json, 'statusCode') ? undefined : json['statusCode'],
        'error': !exists(json, 'error') ? undefined : json['error'],
    };
}

export function ContentResponseToJSON(value?: ContentResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ContentResponseDataToJSON(value.data),
        'statusCode': value.statusCode,
        'error': value.error,
    };
}

