/* tslint:disable */
/* eslint-disable */
/**
 * Makielak API
 * This is a makielak API documentation.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ContentDto } from './ContentDto';
import {
    ContentDtoFromJSON,
    ContentDtoFromJSONTyped,
    ContentDtoToJSON,
} from './ContentDto';

/**
 * 
 * @export
 * @interface ContentResponseData
 */
export interface ContentResponseData {
    /**
     * 
     * @type {ContentDto}
     * @memberof ContentResponseData
     */
    content?: ContentDto;
}

/**
 * Check if a given object implements the ContentResponseData interface.
 */
export function instanceOfContentResponseData(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ContentResponseDataFromJSON(json: any): ContentResponseData {
    return ContentResponseDataFromJSONTyped(json, false);
}

export function ContentResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContentResponseData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'content': !exists(json, 'content') ? undefined : ContentDtoFromJSON(json['content']),
    };
}

export function ContentResponseDataToJSON(value?: ContentResponseData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'content': ContentDtoToJSON(value.content),
    };
}

