/* tslint:disable */
/* eslint-disable */
/**
 * Makielak API
 * This is a makielak API documentation.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ContentDto
 */
export interface ContentDto {
    /**
     * 
     * @type {string}
     * @memberof ContentDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ContentDto
     */
    structure: string;
    /**
     * 
     * @type {string}
     * @memberof ContentDto
     */
    name: ContentDtoNameEnum;
}


/**
 * @export
 */
export const ContentDtoNameEnum = {
    HomePage: 'HOME_PAGE',
    AboutUs: 'ABOUT_US',
    Services: 'SERVICES',
    Certificates: 'CERTIFICATES',
    Contact: 'CONTACT',
    Footer: 'FOOTER'
} as const;
export type ContentDtoNameEnum = typeof ContentDtoNameEnum[keyof typeof ContentDtoNameEnum];


/**
 * Check if a given object implements the ContentDto interface.
 */
export function instanceOfContentDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "structure" in value;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function ContentDtoFromJSON(json: any): ContentDto {
    return ContentDtoFromJSONTyped(json, false);
}

export function ContentDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContentDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'structure': json['structure'],
        'name': json['name'],
    };
}

export function ContentDtoToJSON(value?: ContentDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'structure': value.structure,
        'name': value.name,
    };
}

