/* tslint:disable */
/* eslint-disable */
/**
 * Makielak API
 * This is a makielak API documentation.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DeletedUserResponseData } from './DeletedUserResponseData';
import {
    DeletedUserResponseDataFromJSON,
    DeletedUserResponseDataFromJSONTyped,
    DeletedUserResponseDataToJSON,
} from './DeletedUserResponseData';

/**
 * 
 * @export
 * @interface DeletedUserResponse
 */
export interface DeletedUserResponse {
    /**
     * 
     * @type {DeletedUserResponseData}
     * @memberof DeletedUserResponse
     */
    data?: DeletedUserResponseData;
    /**
     * 
     * @type {number}
     * @memberof DeletedUserResponse
     */
    statusCode?: number;
    /**
     * 
     * @type {string}
     * @memberof DeletedUserResponse
     */
    error?: string;
}

/**
 * Check if a given object implements the DeletedUserResponse interface.
 */
export function instanceOfDeletedUserResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DeletedUserResponseFromJSON(json: any): DeletedUserResponse {
    return DeletedUserResponseFromJSONTyped(json, false);
}

export function DeletedUserResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeletedUserResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : DeletedUserResponseDataFromJSON(json['data']),
        'statusCode': !exists(json, 'statusCode') ? undefined : json['statusCode'],
        'error': !exists(json, 'error') ? undefined : json['error'],
    };
}

export function DeletedUserResponseToJSON(value?: DeletedUserResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': DeletedUserResponseDataToJSON(value.data),
        'statusCode': value.statusCode,
        'error': value.error,
    };
}

