/* tslint:disable */
/* eslint-disable */
/**
 * Makielak API
 * This is a makielak API documentation.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FileDto
 */
export interface FileDto {
    /**
     * 
     * @type {string}
     * @memberof FileDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof FileDto
     */
    type: FileDtoTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof FileDto
     */
    url: string;
}


/**
 * @export
 */
export const FileDtoTypeEnum = {
    Pdf: 'PDF',
    Image: 'IMAGE'
} as const;
export type FileDtoTypeEnum = typeof FileDtoTypeEnum[keyof typeof FileDtoTypeEnum];


/**
 * Check if a given object implements the FileDto interface.
 */
export function instanceOfFileDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "url" in value;

    return isInstance;
}

export function FileDtoFromJSON(json: any): FileDto {
    return FileDtoFromJSONTyped(json, false);
}

export function FileDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': json['type'],
        'url': json['url'],
    };
}

export function FileDtoToJSON(value?: FileDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'type': value.type,
        'url': value.url,
    };
}

