/* tslint:disable */
/* eslint-disable */
/**
 * Makielak API
 * This is a makielak API documentation.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { FileDto } from './FileDto';
import {
    FileDtoFromJSON,
    FileDtoFromJSONTyped,
    FileDtoToJSON,
} from './FileDto';

/**
 * 
 * @export
 * @interface FileResponseData
 */
export interface FileResponseData {
    /**
     * 
     * @type {FileDto}
     * @memberof FileResponseData
     */
    file?: FileDto;
}

/**
 * Check if a given object implements the FileResponseData interface.
 */
export function instanceOfFileResponseData(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function FileResponseDataFromJSON(json: any): FileResponseData {
    return FileResponseDataFromJSONTyped(json, false);
}

export function FileResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileResponseData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'file': !exists(json, 'file') ? undefined : FileDtoFromJSON(json['file']),
    };
}

export function FileResponseDataToJSON(value?: FileResponseData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'file': FileDtoToJSON(value.file),
    };
}

