/* tslint:disable */
/* eslint-disable */
/**
 * Makielak API
 * This is a makielak API documentation.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FooterStructureDto
 */
export interface FooterStructureDto {
    /**
     * 
     * @type {string}
     * @memberof FooterStructureDto
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof FooterStructureDto
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof FooterStructureDto
     */
    firstPhone: string;
    /**
     * 
     * @type {string}
     * @memberof FooterStructureDto
     */
    secondPhone: string;
    /**
     * 
     * @type {string}
     * @memberof FooterStructureDto
     */
    address: string;
}

/**
 * Check if a given object implements the FooterStructureDto interface.
 */
export function instanceOfFooterStructureDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "title" in value;
    isInstance = isInstance && "email" in value;
    isInstance = isInstance && "firstPhone" in value;
    isInstance = isInstance && "secondPhone" in value;
    isInstance = isInstance && "address" in value;

    return isInstance;
}

export function FooterStructureDtoFromJSON(json: any): FooterStructureDto {
    return FooterStructureDtoFromJSONTyped(json, false);
}

export function FooterStructureDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FooterStructureDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': json['title'],
        'email': json['email'],
        'firstPhone': json['firstPhone'],
        'secondPhone': json['secondPhone'],
        'address': json['address'],
    };
}

export function FooterStructureDtoToJSON(value?: FooterStructureDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'email': value.email,
        'firstPhone': value.firstPhone,
        'secondPhone': value.secondPhone,
        'address': value.address,
    };
}

