/* tslint:disable */
/* eslint-disable */
/**
 * Makielak API
 * This is a makielak API documentation.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetUserByIdDto
 */
export interface GetUserByIdDto {
    /**
     * 
     * @type {string}
     * @memberof GetUserByIdDto
     */
    id: string;
}

/**
 * Check if a given object implements the GetUserByIdDto interface.
 */
export function instanceOfGetUserByIdDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function GetUserByIdDtoFromJSON(json: any): GetUserByIdDto {
    return GetUserByIdDtoFromJSONTyped(json, false);
}

export function GetUserByIdDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetUserByIdDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function GetUserByIdDtoToJSON(value?: GetUserByIdDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
    };
}

