/* tslint:disable */
/* eslint-disable */
/**
 * Makielak API
 * This is a makielak API documentation.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetUserByEmailDto
 */
export interface GetUserByEmailDto {
    /**
     * 
     * @type {string}
     * @memberof GetUserByEmailDto
     */
    email: string;
}

/**
 * Check if a given object implements the GetUserByEmailDto interface.
 */
export function instanceOfGetUserByEmailDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "email" in value;

    return isInstance;
}

export function GetUserByEmailDtoFromJSON(json: any): GetUserByEmailDto {
    return GetUserByEmailDtoFromJSONTyped(json, false);
}

export function GetUserByEmailDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetUserByEmailDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
    };
}

export function GetUserByEmailDtoToJSON(value?: GetUserByEmailDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
    };
}

