/* tslint:disable */
/* eslint-disable */
/**
 * Makielak API
 * This is a makielak API documentation.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { FileDto } from './FileDto';
import {
    FileDtoFromJSON,
    FileDtoFromJSONTyped,
    FileDtoToJSON,
} from './FileDto';

/**
 * 
 * @export
 * @interface ServiceItem
 */
export interface ServiceItem {
    /**
     * 
     * @type {string}
     * @memberof ServiceItem
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceItem
     */
    description: string;
    /**
     * 
     * @type {FileDto}
     * @memberof ServiceItem
     */
    image: FileDto;
}

/**
 * Check if a given object implements the ServiceItem interface.
 */
export function instanceOfServiceItem(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "title" in value;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "image" in value;

    return isInstance;
}

export function ServiceItemFromJSON(json: any): ServiceItem {
    return ServiceItemFromJSONTyped(json, false);
}

export function ServiceItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': json['title'],
        'description': json['description'],
        'image': FileDtoFromJSON(json['image']),
    };
}

export function ServiceItemToJSON(value?: ServiceItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'description': value.description,
        'image': FileDtoToJSON(value.image),
    };
}

