/* tslint:disable */
/* eslint-disable */
/**
 * Makielak API
 * This is a makielak API documentation.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StoreFileDto
 */
export interface StoreFileDto {
    /**
     * 
     * @type {string}
     * @memberof StoreFileDto
     */
    type: StoreFileDtoTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof StoreFileDto
     */
    url: string;
}


/**
 * @export
 */
export const StoreFileDtoTypeEnum = {
    Pdf: 'PDF',
    Image: 'IMAGE'
} as const;
export type StoreFileDtoTypeEnum = typeof StoreFileDtoTypeEnum[keyof typeof StoreFileDtoTypeEnum];


/**
 * Check if a given object implements the StoreFileDto interface.
 */
export function instanceOfStoreFileDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "url" in value;

    return isInstance;
}

export function StoreFileDtoFromJSON(json: any): StoreFileDto {
    return StoreFileDtoFromJSONTyped(json, false);
}

export function StoreFileDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoreFileDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'url': json['url'],
    };
}

export function StoreFileDtoToJSON(value?: StoreFileDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'url': value.url,
    };
}

