/* tslint:disable */
/* eslint-disable */
/**
 * Makielak API
 * This is a makielak API documentation.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TokenResponseData } from './TokenResponseData';
import {
    TokenResponseDataFromJSON,
    TokenResponseDataFromJSONTyped,
    TokenResponseDataToJSON,
} from './TokenResponseData';

/**
 * 
 * @export
 * @interface TokenResponse
 */
export interface TokenResponse {
    /**
     * 
     * @type {TokenResponseData}
     * @memberof TokenResponse
     */
    data?: TokenResponseData;
    /**
     * 
     * @type {number}
     * @memberof TokenResponse
     */
    statusCode?: number;
    /**
     * 
     * @type {string}
     * @memberof TokenResponse
     */
    error?: string;
}

/**
 * Check if a given object implements the TokenResponse interface.
 */
export function instanceOfTokenResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TokenResponseFromJSON(json: any): TokenResponse {
    return TokenResponseFromJSONTyped(json, false);
}

export function TokenResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : TokenResponseDataFromJSON(json['data']),
        'statusCode': !exists(json, 'statusCode') ? undefined : json['statusCode'],
        'error': !exists(json, 'error') ? undefined : json['error'],
    };
}

export function TokenResponseToJSON(value?: TokenResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': TokenResponseDataToJSON(value.data),
        'statusCode': value.statusCode,
        'error': value.error,
    };
}

