/* tslint:disable */
/* eslint-disable */
/**
 * Makielak API
 * This is a makielak API documentation.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UserOutDto } from './UserOutDto';
import {
    UserOutDtoFromJSON,
    UserOutDtoFromJSONTyped,
    UserOutDtoToJSON,
} from './UserOutDto';

/**
 * 
 * @export
 * @interface UserResponseData
 */
export interface UserResponseData {
    /**
     * 
     * @type {UserOutDto}
     * @memberof UserResponseData
     */
    user?: UserOutDto;
}

/**
 * Check if a given object implements the UserResponseData interface.
 */
export function instanceOfUserResponseData(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserResponseDataFromJSON(json: any): UserResponseData {
    return UserResponseDataFromJSONTyped(json, false);
}

export function UserResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserResponseData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'user': !exists(json, 'user') ? undefined : UserOutDtoFromJSON(json['user']),
    };
}

export function UserResponseDataToJSON(value?: UserResponseData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'user': UserOutDtoToJSON(value.user),
    };
}

