/* tslint:disable */
/* eslint-disable */
/**
 * Makielak API
 * This is a makielak API documentation.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserOutDto
 */
export interface UserOutDto {
    /**
     * 
     * @type {string}
     * @memberof UserOutDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof UserOutDto
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof UserOutDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof UserOutDto
     */
    role: UserOutDtoRoleEnum;
}


/**
 * @export
 */
export const UserOutDtoRoleEnum = {
    SuperAdmin: 'SUPER_ADMIN',
    Admin: 'ADMIN'
} as const;
export type UserOutDtoRoleEnum = typeof UserOutDtoRoleEnum[keyof typeof UserOutDtoRoleEnum];


/**
 * Check if a given object implements the UserOutDto interface.
 */
export function instanceOfUserOutDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "email" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "role" in value;

    return isInstance;
}

export function UserOutDtoFromJSON(json: any): UserOutDto {
    return UserOutDtoFromJSONTyped(json, false);
}

export function UserOutDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserOutDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'email': json['email'],
        'name': json['name'],
        'role': json['role'],
    };
}

export function UserOutDtoToJSON(value?: UserOutDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'email': value.email,
        'name': value.name,
        'role': value.role,
    };
}

