/* tslint:disable */
/* eslint-disable */
/**
 * Makielak API
 * This is a makielak API documentation.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UserResponseData } from './UserResponseData';
import {
    UserResponseDataFromJSON,
    UserResponseDataFromJSONTyped,
    UserResponseDataToJSON,
} from './UserResponseData';

/**
 * 
 * @export
 * @interface UserResponse
 */
export interface UserResponse {
    /**
     * 
     * @type {UserResponseData}
     * @memberof UserResponse
     */
    data?: UserResponseData;
    /**
     * 
     * @type {number}
     * @memberof UserResponse
     */
    statusCode?: number;
    /**
     * 
     * @type {string}
     * @memberof UserResponse
     */
    error?: string;
}

/**
 * Check if a given object implements the UserResponse interface.
 */
export function instanceOfUserResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserResponseFromJSON(json: any): UserResponse {
    return UserResponseFromJSONTyped(json, false);
}

export function UserResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : UserResponseDataFromJSON(json['data']),
        'statusCode': !exists(json, 'statusCode') ? undefined : json['statusCode'],
        'error': !exists(json, 'error') ? undefined : json['error'],
    };
}

export function UserResponseToJSON(value?: UserResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': UserResponseDataToJSON(value.data),
        'statusCode': value.statusCode,
        'error': value.error,
    };
}

