/* tslint:disable */
/* eslint-disable */
/**
 * Makielak API
 * This is a makielak API documentation.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UserOutDto } from './UserOutDto';
import {
    UserOutDtoFromJSON,
    UserOutDtoFromJSONTyped,
    UserOutDtoToJSON,
} from './UserOutDto';

/**
 * 
 * @export
 * @interface UsersResponseData
 */
export interface UsersResponseData {
    /**
     * 
     * @type {Array<UserOutDto>}
     * @memberof UsersResponseData
     */
    users?: Array<UserOutDto>;
}

/**
 * Check if a given object implements the UsersResponseData interface.
 */
export function instanceOfUsersResponseData(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UsersResponseDataFromJSON(json: any): UsersResponseData {
    return UsersResponseDataFromJSONTyped(json, false);
}

export function UsersResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersResponseData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'users': !exists(json, 'users') ? undefined : ((json['users'] as Array<any>).map(UserOutDtoFromJSON)),
    };
}

export function UsersResponseDataToJSON(value?: UsersResponseData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'users': value.users === undefined ? undefined : ((value.users as Array<any>).map(UserOutDtoToJSON)),
    };
}

